export const timePageElements = {
    timeMenuButton:':nth-child(4) > .oxd-main-menu-item',
    employeeName:'.oxd-autocomplete-text-input > input',
    employeeNameOption:'.oxd-autocomplete-option', 
    viewButton:'.oxd-form-actions > .oxd-button',
    actionViewButton:':nth-child(1) > .oxd-table-row > [style="flex: 1 1 20%;"] > .oxd-table-cell-actions > .oxd-button',
    calendarButton:'.oxd-date-input > .oxd-input',
    nextButton:'.--next',
    prevButton:'.--prev',
    editButton:'.orangehrm-timesheet-footer--options > .oxd-button',
    projectInput:':nth-child(1) > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-autocomplete-wrapper > .oxd-autocomplete-text-input > input',
    projectOption1:'.oxd-autocomplete-dropdown > :nth-child(1) > span', //FreeWave Technologies, Inc. - FWT - Phase 1
    projectOption2:'.oxd-autocomplete-dropdown > :nth-child(2)', //Internal - General HR Tasks
    activityDropdown:':nth-child(1) > :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text',
    bugFixesOption:'.oxd-select-dropdown > :nth-child(2)',
    monInput:':nth-child(1) > :nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input',
    tueInput:':nth-child(1) > :nth-child(4) > .oxd-input-group > :nth-child(2) > .oxd-input',
    wedInput:':nth-child(1) > :nth-child(5) > .oxd-input-group > :nth-child(2) > .oxd-input',
    thuInput:':nth-child(1) > :nth-child(6) > .oxd-input-group > :nth-child(2) > .oxd-input',
    friInput:':nth-child(1) > :nth-child(7) > .oxd-input-group > :nth-child(2) > .oxd-input',
    satInput:':nth-child(1) > :nth-child(8) > .oxd-input-group > :nth-child(2) > .oxd-input',
    sunInput:':nth-child(1) > :nth-child(9) > .oxd-input-group > :nth-child(2) > .oxd-input',
    deletButton:':nth-child(1) > .--flex > .oxd-icon-button',
    resetButton:'.orangehrm-timesheet-footer--options > :nth-child(2)',
    cancelButton:'.orangehrm-timesheet-footer--options > :nth-child(1)',
    addNewRowButton:':nth-child(2) > .orangehrm-timesheet-table-body-cell',
    createTimesheet:'.oxd-button',
    noTimesheetAlert:'.oxd-text oxd-text--p oxd-alert-content-text',
    timesheetForUser:'.orangehrm-timesheet-header--title > .oxd-text',
    submitButton:'.oxd-button--secondary',
    commentBox:'.oxd-textarea',
    approveButton:'.oxd-button--success',
    rejectButton:'.oxd-button--danger',
    resetButton1:'.oxd-button',
    editButton1:'.oxd-button--ghost'
}